import { Project, Task, MaterialRequest, IssueReport, SiteUpdate, ProjectFile } from './types';

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'Shah Residence',
    client: 'Rajesh & Neha Shah',
    clientPhone: '+91 98201 45210',
    progress: 78,
    deadline: '15 Oct 2026',
    status: 'On Track',
    siteManager: 'Ramesh Kumar',
    managerPhone: '+91 98450 11234',
    address: 'Flat 4201, Imperial Towers, Tardeo, Mumbai',
    type: 'Luxury 4BHK Penthouse',
    area: '4,450 sq.ft',
    startDate: '10 Jun 2026',
    imageUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1000&q=80',
    budgetSpent: '₹72,50,000',
    totalBudget: '₹95,00,000',
    currentPhase: 'Phase 3 of 5: Fixed Millwork, Paneling & MEP Fitouts',
    workersOnSiteCount: 18,
    workersBreakdown: '6 Carpenters, 4 Electricians, 3 Plumbers, 2 Polishers, 3 General Helpers',
    notes: 'Premium imported Italian Statuario marble in living room; teak acoustic fluting in home theater.',
    rooms: [
      { name: 'Living & Dining Foyer', stage: 'Veneer Polishing & Trim', progress: 90 },
      { name: 'Master Suite & Walk-in', stage: 'Wardrobe Hardware & Shutter Fitment', progress: 82 },
      { name: 'Home Theater', stage: 'Fabric Acoustic Paneling', progress: 70 },
      { name: 'Modular Kitchen', stage: 'Countertop Quartz & Hob installation', progress: 85 },
      { name: 'Guest Bedrooms (2)', stage: 'POP False Ceiling & 1st Coat Paint', progress: 65 },
    ],
    milestones: [
      { id: 'm1', name: 'Civil & MEP Rough-ins', progress: 100, status: 'Completed', targetDate: '15 Jul 2026' },
      { id: 'm2', name: 'False Ceiling & Gypsum Framework', progress: 100, status: 'Completed', targetDate: '10 Aug 2026' },
      { id: 'm3', name: 'Fixed Woodwork & Core Carpentry', progress: 85, status: 'In Progress', targetDate: '20 Sep 2026' },
      { id: 'm4', name: 'Painting & Surface Treatments', progress: 50, status: 'In Progress', targetDate: '02 Oct 2026' },
      { id: 'm5', name: 'Lighting, Sanitary & Handover Deep Clean', progress: 20, status: 'Upcoming', targetDate: '15 Oct 2026' },
    ],
  },
  {
    id: 'proj-2',
    name: 'Patel Office',
    client: 'Keyur Patel (Apex Capital)',
    clientPhone: '+91 98110 99421',
    progress: 61,
    deadline: '28 Sep 2026',
    status: 'Delayed',
    siteManager: 'Vikram Singh',
    managerPhone: '+91 97230 44551',
    address: '8th Floor, One BKC, Bandra Kurla Complex, Mumbai',
    type: 'Boutique Financial HQ',
    area: '6,200 sq.ft',
    startDate: '01 May 2026',
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1000&q=80',
    budgetSpent: '₹1,15,00,000',
    totalBudget: '₹1,60,00,000',
    currentPhase: 'Phase 4 of 5: Wall Cladding, Glazing & Modular Raceway Lay',
    workersOnSiteCount: 24,
    workersBreakdown: '8 Glaziers/Gypsum, 6 Network Techs, 4 HVAC crew, 6 Helpers',
    notes: 'Delayed by 6 days due to customs clearance of Italian fluted walnut panels for Boardroom.',
    rooms: [
      { name: 'Reception & Waiting Lounge', stage: 'Stone Cladding & Logo Backlit wall', progress: 75 },
      { name: 'Executive Boardroom', stage: 'Awaiting Fluted Walnut Wall Paneling', progress: 45 },
      { name: 'Open Workstation Floor (40pax)', stage: 'Modular raceways & carpet tile lay', progress: 70 },
      { name: 'Partner Cabins (3)', stage: 'Glass acoustic partition glazing', progress: 60 },
      { name: 'Cafeteria & Wellness Corner', stage: 'Subway tile backsplash & laminate', progress: 55 },
    ],
    milestones: [
      { id: 'm21', name: 'HVAC Ducting & Fire Sprinkler Grid', progress: 100, status: 'Completed', targetDate: '15 Jun 2026' },
      { id: 'm22', name: 'Electrical conduits & Server Room Cable Trays', progress: 100, status: 'Completed', targetDate: '05 Jul 2026' },
      { id: 'm23', name: 'Glass Partitions & Wall Framework', progress: 75, status: 'In Progress', targetDate: '30 Aug 2026' },
      { id: 'm24', name: 'Custom Millwork & Boardroom Paneling', progress: 40, status: 'In Progress', targetDate: '15 Sep 2026' },
      { id: 'm25', name: 'Modular Desking, Signage & Snagging', progress: 15, status: 'Upcoming', targetDate: '28 Sep 2026' },
    ],
  },
  {
    id: 'proj-3',
    name: 'Mehta Villa',
    client: 'Ananya & Dr. Sameer Mehta',
    clientPhone: '+91 98332 88712',
    progress: 42,
    deadline: '20 Nov 2026',
    status: 'On Track',
    siteManager: 'Ramesh Kumar',
    managerPhone: '+91 98450 11234',
    address: 'Plot 14, Mandwa Coastal Greens, Alibaug',
    type: '5BHK Coastal Retreat Villa',
    area: '7,800 sq.ft',
    startDate: '20 Jul 2026',
    imageUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1000&q=80',
    budgetSpent: '₹64,00,000',
    totalBudget: '₹1,85,00,000',
    currentPhase: 'Phase 2 of 5: Concealed MEP Chasing & Waterproofing',
    workersOnSiteCount: 14,
    workersBreakdown: '4 Waterproofing Techs, 4 Masons, 3 Electricians, 3 Helpers',
    notes: 'Exposed lime plaster finish on double-height living room walls; natural teak pergola on terrace.',
    rooms: [
      { name: 'Double-Height Living Pavilion', stage: 'False ceiling framing & AC copper pipes', progress: 50 },
      { name: 'Master Villa Suite', stage: 'Waterproofing & under-tile screed', progress: 45 },
      { name: 'Outdoor Verandah & Deck', stage: 'Treated Ipe wood sub-structure', progress: 35 },
      { name: 'Kitchen & Utility Courtyard', stage: 'Civil adjustments & granite countertop', progress: 40 },
      { name: 'Guest Cottages (2 wings)', stage: 'Concealed electrical chasing', progress: 40 },
    ],
    milestones: [
      { id: 'm31', name: 'Structural Civil Handover & Waterproofing', progress: 100, status: 'Completed', targetDate: '10 Aug 2026' },
      { id: 'm32', name: 'Concealed MEP Plumbing & Electrical', progress: 70, status: 'In Progress', targetDate: '20 Sep 2026' },
      { id: 'm33', name: 'Gypsum Ceilings & Micro-cement prep', progress: 30, status: 'In Progress', targetDate: '10 Oct 2026' },
      { id: 'm34', name: 'Flooring, Stone & Custom Joinery', progress: 10, status: 'Upcoming', targetDate: '05 Nov 2026' },
      { id: 'm35', name: 'Fixtures, Landscape Lighting & Handover', progress: 0, status: 'Upcoming', targetDate: '20 Nov 2026' },
    ],
  },
];

export const INITIAL_TASKS: Task[] = [
  // Shah Residence (Ramesh Kumar supervisor) - covering all 8 categories
  {
    id: 'task-1',
    projectId: 'proj-1',
    projectName: 'Shah Residence',
    title: 'Install 24V COB LED aluminum profiles in living room false ceiling',
    room: 'Living & Dining Foyer',
    assignedTo: 'Sunil Verma (Lead Electrician)',
    startDate: '05 Sep 2026',
    deadline: 'Today, 4:00 PM',
    dueDate: 'Today, 4:00 PM',
    priority: 'High',
    progress: 75,
    status: 'In Progress',
    isCompleted: false,
    photos: ['https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=600&q=80'],
    notes: 'Ensure 3000K warm white strip is used; avoid shadows near the curtain pelmet recess.',
    instructions: '1. Check false ceiling aluminum channel for level.\n2. Cut 24V COB LED strip only along marked solder points.\n3. Mount driver in the accessible trap door near switchboard.\n4. Test strip with multimeter before snapping diffuser cap.',
    referenceImages: [
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80'
    ],
    category: 'Electrical',
  },
  {
    id: 'task-2',
    projectId: 'proj-1',
    projectName: 'Shah Residence',
    title: 'Check veneer bookmatch grain alignment on Master wardrobe shutters',
    room: 'Master Suite',
    assignedTo: 'Kishan Mistri (Carpentry)',
    startDate: '02 Sep 2026',
    deadline: 'Today, 2:30 PM',
    dueDate: 'Today, 2:30 PM',
    priority: 'High',
    progress: 100,
    status: 'Completed',
    isCompleted: true,
    photos: ['https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=600&q=80'],
    notes: 'Veneer batch #440 matches sample board approved by client on Saturday.',
    instructions: '1. Lay out all 4 wardrobe shutter panels in sequence.\n2. Verify continuous bookmatch grain flow across center splits.\n3. Apply PU sealer along edge bands to prevent moisture absorption.\n4. Have supervisor inspect under site floodlights.',
    referenceImages: [
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=800&q=80'
    ],
    category: 'Carpentry',
  },
  {
    id: 'task-3',
    projectId: 'proj-1',
    projectName: 'Shah Residence',
    title: 'Repair CPVC joint and verify pressure test at Master Bath service shaft',
    room: 'Master Bathroom',
    assignedTo: 'Manoj Yadav (Plumbing Tech)',
    startDate: '06 Sep 2026',
    deadline: 'Today, 6:00 PM',
    dueDate: 'Today, 6:00 PM',
    priority: 'High',
    progress: 40,
    status: 'In Progress',
    isCompleted: false,
    photos: ['https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80'],
    notes: 'Keep pressure gauge at 6 bar for 24h before screed closing.',
    instructions: '1. Isolate the main water riser valve on terrace.\n2. Cut damaged CPVC elbow cleanly at 90 degrees with pipe shears.\n3. Ream interior burrs and apply heavy duty CPVC solvent cement.\n4. Pressurize system to 6 bar and check gauge needle after 3 hours.',
    referenceImages: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80'
    ],
    category: 'Plumbing',
  },
  {
    id: 'task-4',
    projectId: 'proj-1',
    projectName: 'Shah Residence',
    title: 'Perimeter shadowline groove & AC return air grille framing',
    room: 'Living Room',
    assignedTo: 'Gypsum Specialist Team',
    startDate: '03 Sep 2026',
    deadline: '08 Sep 2026',
    dueDate: '08 Sep 2026',
    priority: 'Medium',
    progress: 90,
    status: 'Review',
    isCompleted: false,
    photos: ['https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=600&q=80'],
    notes: 'Awaiting designer sign-off on 15mm reveal gap along perimeter beam.',
    category: 'Ceiling',
  },
  {
    id: 'task-5',
    projectId: 'proj-1',
    projectName: 'Shah Residence',
    title: 'Ponding water test on kitchen utility sunken slab',
    room: 'Modular Kitchen & Utility',
    assignedTo: 'Ramesh Kumar (Civil Sub)',
    startDate: '01 Sep 2026',
    deadline: '04 Sep 2026',
    dueDate: '04 Sep 2026',
    priority: 'High',
    progress: 100,
    status: 'Completed',
    isCompleted: true,
    photos: ['https://images.unsplash.com/photo-1541888946425-d0fbb186156a?auto=format&fit=crop&w=600&q=80'],
    notes: 'Zero water drop recorded after 48-hour continuous standing head.',
    category: 'Civil',
  },
  {
    id: 'task-6',
    projectId: 'proj-1',
    projectName: 'Shah Residence',
    title: 'Apply 2nd coat acrylic primer & putty sanding in Guest Bedrooms',
    room: 'Guest Bedrooms (2)',
    assignedTo: 'Asian Paints Pro Crew',
    startDate: '06 Sep 2026',
    deadline: '10 Sep 2026',
    dueDate: '10 Sep 2026',
    priority: 'Medium',
    progress: 30,
    status: 'In Progress',
    isCompleted: false,
    photos: ['https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&w=600&q=80'],
    notes: 'Royale Aspira silk matte finish sample patch created on east wall.',
    category: 'Painting',
  },
  {
    id: 'task-7',
    projectId: 'proj-1',
    projectName: 'Shah Residence',
    title: 'Unpack & inspect custom curved boucle sofa frame and brass base plinth',
    room: 'Formal Living Room',
    assignedTo: 'Studio Logistics Team',
    startDate: '12 Sep 2026',
    deadline: '15 Sep 2026',
    dueDate: '15 Sep 2026',
    priority: 'Low',
    progress: 0,
    status: 'Waiting',
    isCompleted: false,
    photos: [],
    notes: 'Holding in central warehouse until second coat paint is dry on site.',
    category: 'Furniture',
  },
  {
    id: 'task-8',
    projectId: 'proj-1',
    projectName: 'Shah Residence',
    title: 'Sand and apply 1st coat PU matte sealer on dining display teak frame',
    room: 'Dining Area',
    assignedTo: 'Iqbal Polishing Crew',
    startDate: '06 Sep 2026',
    deadline: 'Tomorrow, 11:00 AM',
    dueDate: 'Tomorrow, 11:00 AM',
    priority: 'Medium',
    progress: 50,
    status: 'In Progress',
    isCompleted: false,
    photos: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80'],
    notes: 'Ensure dust extraction extractor is on to protect wet coat.',
    category: 'Finishing',
  },

  // Patel Office (Vikram Singh supervisor)
  {
    id: 'task-9',
    projectId: 'proj-2',
    projectName: 'Patel Office',
    title: 'Complete acoustic rockwool insulation packing in Boardroom drywall',
    room: 'Executive Boardroom',
    assignedTo: 'Vikram Singh (Gypsum Crew)',
    startDate: '04 Sep 2026',
    deadline: 'Today, 5:00 PM',
    dueDate: 'Today, 5:00 PM',
    priority: 'High',
    progress: 65,
    status: 'In Progress',
    isCompleted: false,
    notes: 'Crucial for STC 48 acoustic rating requirement from client.',
    category: 'Civil',
  },
  {
    id: 'task-10',
    projectId: 'proj-2',
    projectName: 'Patel Office',
    title: 'Inspect floor core-cutting for under-desk network grommets',
    room: 'Workstation Floor',
    assignedTo: 'Vikram Singh',
    startDate: '05 Sep 2026',
    deadline: 'Today, 1:00 PM',
    dueDate: 'Today, 1:00 PM',
    priority: 'High',
    progress: 100,
    status: 'Completed',
    isCompleted: true,
    notes: 'All 12 floor points checked against architect drawing revision Rev-3B.',
    category: 'Electrical',
  },
  {
    id: 'task-11',
    projectId: 'proj-2',
    projectName: 'Patel Office',
    title: 'Grid ceiling acoustic perforated metal tile drop fitment',
    room: 'Open Workstation Floor',
    assignedTo: 'Armstrong Grid Specialist',
    startDate: '07 Sep 2026',
    deadline: '12 Sep 2026',
    dueDate: '12 Sep 2026',
    priority: 'Medium',
    progress: 40,
    status: 'In Progress',
    isCompleted: false,
    category: 'Ceiling',
  },
  {
    id: 'task-12',
    projectId: 'proj-2',
    projectName: 'Patel Office',
    title: 'Install emergency exit signage wiring & test sensor loops',
    room: 'Lobby Corridor',
    assignedTo: 'Fire Safety Tech',
    startDate: '08 Sep 2026',
    deadline: 'Tomorrow, 5:00 PM',
    dueDate: 'Tomorrow, 5:00 PM',
    priority: 'Medium',
    progress: 0,
    status: 'Not Started',
    isCompleted: false,
    category: 'Electrical',
  },
  {
    id: 'task-13',
    projectId: 'proj-2',
    projectName: 'Patel Office',
    title: 'Seal glass partition perimeter joints with black silicone gasket',
    room: 'Partner Cabins',
    assignedTo: 'Glazing Subcontractor',
    startDate: '06 Sep 2026',
    deadline: 'Tomorrow, 2:00 PM',
    dueDate: 'Tomorrow, 2:00 PM',
    priority: 'Medium',
    progress: 25,
    status: 'In Progress',
    isCompleted: false,
    category: 'Finishing',
  },

  // Mehta Villa (Ramesh Kumar supervisor)
  {
    id: 'task-14',
    projectId: 'proj-3',
    projectName: 'Mehta Villa',
    title: 'Complete second coat bitumen waterproofing in courtyard sunken slab',
    room: 'Courtyard & Deck',
    assignedTo: 'Ramesh Kumar (Waterproofing Crew)',
    startDate: '05 Sep 2026',
    deadline: 'Today, 4:30 PM',
    dueDate: 'Today, 4:30 PM',
    priority: 'High',
    progress: 80,
    status: 'In Progress',
    isCompleted: false,
    notes: 'Ponding test required on Wednesday morning before tile bed screed.',
    category: 'Civil',
  },
  {
    id: 'task-15',
    projectId: 'proj-3',
    projectName: 'Mehta Villa',
    title: 'Mark AC drain slope pipes inside living pavilion double-height ceiling',
    room: 'Living Pavilion',
    assignedTo: 'HVAC Team',
    startDate: '07 Sep 2026',
    deadline: 'Tomorrow, 10:00 AM',
    dueDate: 'Tomorrow, 10:00 AM',
    priority: 'Medium',
    progress: 0,
    status: 'Not Started',
    isCompleted: false,
    category: 'Plumbing',
  },
  {
    id: 'task-16',
    projectId: 'proj-3',
    projectName: 'Mehta Villa',
    title: 'Deliver 12mm marine ply sheets batch #2 to carpenter workshop zone',
    room: 'Site Store',
    assignedTo: 'Site Logistics',
    startDate: '06 Sep 2026',
    deadline: 'Tomorrow, 12:00 PM',
    dueDate: 'Tomorrow, 12:00 PM',
    priority: 'Medium',
    progress: 50,
    status: 'Waiting',
    isCompleted: false,
    category: 'Carpentry',
  },
  {
    id: 'task-17',
    projectId: 'proj-3',
    projectName: 'Mehta Villa',
    title: 'Client site walkthrough with Architect Archana Sengupta',
    room: 'All Zones',
    assignedTo: 'Ramesh Kumar',
    startDate: '09 Sep 2026',
    deadline: 'Friday, 11:00 AM',
    dueDate: 'Friday, 11:00 AM',
    priority: 'High',
    progress: 0,
    status: 'Not Started',
    isCompleted: false,
    notes: 'Review lime wash mockups and terrace pergola placement.',
    category: 'Finishing',
  },
];

export const INITIAL_MATERIAL_REQUESTS: MaterialRequest[] = [
  {
    id: 'mat-1',
    projectId: 'proj-1',
    projectName: 'Shah Residence',
    itemName: 'Warm White 24V COB LED Strips (3000K, 95+ CRI)',
    quantity: '60 meters (6 rolls) + 3 drivers',
    category: 'Lighting & Electrical',
    requestedBy: 'Ramesh Kumar',
    requestedDate: 'Today, 09:15 AM',
    urgency: 'Urgent',
    status: 'Pending',
    specs: 'Philips Lumileds or Osram 24V DC IP20, continuous dotless profile',
    vendor: 'Luxe Illuminations Bandra',
    estimatedCost: '₹28,500',
  },
  {
    id: 'mat-2',
    projectId: 'proj-2',
    projectName: 'Patel Office',
    itemName: 'Italian Fluted Walnut Paneling (Flame Retardant B1)',
    quantity: '18 panels (8ft x 2ft)',
    category: 'Woodwork & Millwork',
    requestedBy: 'Vikram Singh',
    requestedDate: 'Yesterday, 04:30 PM',
    urgency: 'Urgent',
    status: 'Pending',
    specs: 'Natural American Walnut stain, matte polyurethane factory finish',
    vendor: 'DecoTimber Imports',
    estimatedCost: '₹1,45,000',
  },
  {
    id: 'mat-3',
    projectId: 'proj-1',
    projectName: 'Shah Residence',
    itemName: 'Blum Clip-Top 110° Concealed Hinges with Soft-Close',
    quantity: '48 pairs + mounting plates',
    category: 'Hardware',
    requestedBy: 'Ramesh Kumar',
    requestedDate: 'Yesterday, 11:20 AM',
    urgency: 'Medium',
    status: 'Pending',
    specs: 'Onyx Black finish for dark wood shutters',
    vendor: 'Hafele Direct Gallery',
    estimatedCost: '₹34,000',
  },
  {
    id: 'mat-4',
    projectId: 'proj-3',
    projectName: 'Mehta Villa',
    itemName: 'Fosroc Brushbond Roof & Wet-Area Waterproofing Slurry',
    quantity: '10 bags (25kg each) + 50L polymer',
    category: 'Civil & Waterproofing',
    requestedBy: 'Ramesh Kumar',
    requestedDate: '04 Sep 2026',
    urgency: 'High',
    status: 'Pending',
    specs: 'Two-component elastomeric acrylic polymer modified membrane',
    vendor: 'Reliable Building Supplies',
    estimatedCost: '₹42,000',
  },
  {
    id: 'mat-5',
    projectId: 'proj-2',
    projectName: 'Patel Office',
    itemName: 'Shaw Contract Acoustic Carpet Tiles (Charcoal Heather)',
    quantity: '450 sq. meters',
    category: 'Flooring',
    requestedBy: 'Vikram Singh',
    requestedDate: '03 Sep 2026',
    urgency: 'Medium',
    status: 'Pending',
    specs: 'EcoWorx backing, 50x50cm, multi-level loop tufted nylon',
    vendor: 'Span Floors Corp',
    estimatedCost: '₹3,20,000',
  },
];

export const INITIAL_ISSUES: IssueReport[] = [
  {
    id: 'issue-1',
    projectId: 'proj-1',
    projectName: 'Shah Residence',
    category: 'Plumbing',
    priority: 'Urgent',
    status: 'Open',
    title: 'Minor seepage detected near Master Bathroom vertical plumbing shaft',
    description: 'During 6-bar pressure testing, a minute drip was observed at the hot-water CPVC joint inside the service shaft. The joint needs re-brazing before the duct shaft is sealed with waterproof cement board.',
    room: 'Master Bathroom Shaft',
    severity: 'Critical',
    reportedBy: 'Ramesh Kumar',
    reportedAt: 'Today, 08:30 AM',
    assignedTo: 'Plumbing Subcontractor (Sunil M.)',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
    actionTaken: 'Water inlet turned off temporarily. Sunil instructed to replace 25mm elbow joint by 2 PM.',
    relatedTaskId: 'task-5',
    relatedTaskTitle: 'Ponding water test on kitchen utility sunken slab',
    comments: [
      {
        id: 'comm-1',
        author: 'Ramesh Kumar',
        authorRole: 'Site Supervisor',
        text: 'Isolated main ball valve on floor 3. No leakage spreading into master bedroom ceiling.',
        createdAt: 'Today, 08:45 AM',
      },
      {
        id: 'comm-2',
        author: 'Archana Sengupta',
        authorRole: 'Studio Principal',
        text: 'Sunil must use heavy-gauge solvent weld fittings only. Re-test at 8 bar before closing the duct.',
        createdAt: 'Today, 09:10 AM',
      },
    ],
  },
  {
    id: 'issue-2',
    projectId: 'proj-2',
    projectName: 'Patel Office',
    category: 'Material',
    priority: 'Urgent',
    status: 'Open',
    title: 'Customs clearance hold on Boardroom fluted walnut panels',
    description: 'Shipment batch stuck at Nhava Sheva port for additional phytosanitary paperwork verification. Delays Boardroom wall completion by 6 days. Need architect approval to resequence modular desking installation first.',
    room: 'Executive Boardroom',
    severity: 'Critical',
    reportedBy: 'Vikram Singh',
    reportedAt: 'Yesterday, 02:15 PM',
    assignedTo: 'Apex Logistics & Archana Sengupta',
    actionTaken: 'Clearing agent submitted revised timber certificate. Revised port release expected Thursday.',
    comments: [
      {
        id: 'comm-3',
        author: 'Vikram Singh',
        authorRole: 'Site Supervisor',
        text: 'Customs broker requested original fumigation stamp certificate from Italian supplier.',
        createdAt: 'Yesterday, 03:00 PM',
      },
    ],
  },
  {
    id: 'issue-3',
    projectId: 'proj-1',
    projectName: 'Shah Residence',
    category: 'Carpentry',
    priority: 'High',
    status: 'In Progress',
    title: 'Veneer grain mismatch on master wardrobe 3rd shutter panel',
    description: 'The natural smoked oak veneer grain direction is running diagonally across shutter #3 while adjacent shutters are bookmatched vertically. Shutter needs remaking before PU lacquer polishing.',
    room: 'Master Suite Wardrobe',
    severity: 'Medium',
    reportedBy: 'Ramesh Kumar',
    reportedAt: 'Yesterday, 11:20 AM',
    assignedTo: 'DecoTimber Woodwork (Mahesh)',
    imageUrl: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=800&q=80',
    actionTaken: 'New sheet of matching flitch marked at factory warehouse for hot-press.',
    relatedTaskId: 'task-1',
    relatedTaskTitle: 'Install custom fluted oak veneer paneling in Master Suite',
    comments: [
      {
        id: 'comm-4',
        author: 'Archana Sengupta',
        authorRole: 'Studio Principal',
        text: 'Inspected flitch photos. Batch #B4 is approved. Factory delivery scheduled for tomorrow morning.',
        createdAt: 'Yesterday, 04:30 PM',
      },
    ],
  },
  {
    id: 'issue-4',
    projectId: 'proj-3',
    projectName: 'Mehta Villa',
    category: 'Electrical',
    priority: 'Normal',
    status: 'In Progress',
    title: 'AC thermostat wall cut-out clash with architectural brass reveal',
    description: 'Thermostat conduit location clashes with the 50mm bronze shadow gap profile detailed on drawing WD-04. Needs 75mm lateral shift to clear metal channel.',
    room: 'Living Pavilion',
    severity: 'Medium',
    reportedBy: 'Ramesh Kumar',
    reportedAt: '05 Sep 2026, 03:40 PM',
    assignedTo: 'HVAC & MEP Sub (Rajesh Electricals)',
    relatedTaskId: 'task-15',
    relatedTaskTitle: 'Mark AC drain slope pipes inside living pavilion double-height ceiling',
    comments: [
      {
        id: 'comm-5',
        author: 'Rajesh Sharma',
        authorRole: 'MEP Subcontractor',
        text: 'Chiseled 75mm to the left, rerouted flexible conduit. Waiting for plaster touchup.',
        createdAt: '06 Sep 2026, 10:00 AM',
      },
    ],
  },
  {
    id: 'issue-5',
    projectId: 'proj-1',
    projectName: 'Shah Residence',
    category: 'Safety',
    priority: 'Urgent',
    status: 'Resolved',
    title: 'Unshielded temporary DB power cable across hallway walkway',
    description: 'High voltage 3-phase extension cable running across high-traffic transition corridor without heavy-duty rubber cable ramp. Slip and electrocution hazard.',
    room: 'Main Foyer Corridor',
    severity: 'Critical',
    reportedBy: 'Ramesh Kumar',
    reportedAt: '04 Sep 2026, 09:00 AM',
    assignedTo: 'Site Safety Officer & Ramesh',
    actionTaken: 'Installed yellow rubber crossover cable protector ramp and overhead cable suspension hooks.',
    comments: [
      {
        id: 'comm-6',
        author: 'Ramesh Kumar',
        authorRole: 'Site Supervisor',
        text: 'Cables hung along ceiling level using insulated insulated J-hooks. Hazard eliminated.',
        createdAt: '04 Sep 2026, 11:15 AM',
      },
    ],
  },
  {
    id: 'issue-6',
    projectId: 'proj-2',
    projectName: 'Patel Office',
    category: 'Civil',
    priority: 'Normal',
    status: 'Resolved',
    title: 'Screed unevenness near server room threshold (>6mm depression)',
    description: 'Self-leveling compound required prior to anti-static vinyl flooring installation in server farm area.',
    room: 'Server & IT Control Room',
    severity: 'Low',
    reportedBy: 'Vikram Singh',
    reportedAt: '02 Sep 2026, 01:15 PM',
    assignedTo: 'Flooring Contractor',
    actionTaken: 'Applied Ardex self-smoothing screed. Laser level verification passed with <1mm deviation.',
  },
];

export const INITIAL_UPDATES: SiteUpdate[] = [
  {
    id: 'up-1',
    projectId: 'proj-1',
    projectName: 'Shah Residence',
    author: 'Ramesh Kumar',
    authorRole: 'Site Supervisor',
    timestamp: '25 mins ago',
    room: 'Living & Dining Foyer',
    description: 'Italian Statuario marble flooring completed with mirror diamond polish finish. Paper protection sheets laid down immediately to avoid scratches from upcoming painting scaffolding.',
    type: 'Progress',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    progressPercentage: 78,
    tags: ['Flooring', 'Living Room', 'Quality Check'],
  },
  {
    id: 'up-2',
    projectId: 'proj-2',
    projectName: 'Patel Office',
    author: 'Vikram Singh',
    authorRole: 'Site Supervisor',
    timestamp: '2 hours ago',
    room: 'Open Workstation Floor',
    description: 'Under-floor electrical conduits and Cat6A LAN cable pull finished for all 40 desks. Server rack terminations tested and certified by IT consultant.',
    type: 'Inspection',
    imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=800&q=80',
    progressPercentage: 61,
    tags: ['Electrical', 'IT Infrastructure', 'Passed'],
  },
  {
    id: 'up-3',
    projectId: 'proj-1',
    projectName: 'Shah Residence',
    author: 'Ramesh Kumar',
    authorRole: 'Site Supervisor',
    timestamp: '4 hours ago',
    room: 'Master Bathroom',
    description: 'Plumbing leak detected at service duct during 6-bar test. Reported as urgent issue #issue-1. Water main isolated.',
    type: 'Snag',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
    tags: ['Snag', 'Plumbing', 'Action Required'],
  },
  {
    id: 'up-4',
    projectId: 'proj-3',
    projectName: 'Mehta Villa',
    author: 'Ramesh Kumar',
    authorRole: 'Site Supervisor',
    timestamp: 'Yesterday, 05:45 PM',
    room: 'Living Pavilion',
    description: 'Double-height ceiling gypsum channels completed. AC cassette fan coil units suspended with vibration isolation dampers.',
    type: 'Photo',
    imageUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80',
    progressPercentage: 42,
    tags: ['HVAC', 'False Ceiling', 'Milestone'],
  },
];

export const INITIAL_FILES: ProjectFile[] = [
  // Shah Residence
  {
    id: 'file-1',
    projectId: 'proj-1',
    name: 'GFC_Architectural_FloorPlan_Rev4.dwg',
    category: 'Drawings & CAD',
    fileType: 'DWG',
    size: '14.2 MB',
    uploadedAt: '12 Jun 2026',
    uploadedBy: 'Studio Atelier',
  },
  {
    id: 'file-2',
    projectId: 'proj-1',
    name: 'False_Ceiling_Reflected_Lighting_Plan_v2.pdf',
    category: 'Drawings & CAD',
    fileType: 'PDF',
    size: '4.8 MB',
    uploadedAt: '05 Aug 2026',
    uploadedBy: 'Studio Atelier',
  },
  {
    id: 'file-3',
    projectId: 'proj-1',
    name: 'Modular_Kitchen_Hardware_Cutlist_Blum.pdf',
    category: 'Joinery & Millwork',
    fileType: 'PDF',
    size: '2.1 MB',
    uploadedAt: '18 Aug 2026',
    uploadedBy: 'Ramesh Kumar',
  },
  {
    id: 'file-4',
    projectId: 'proj-1',
    name: 'Master_Bath_Sanitary_MEP_Schematic.pdf',
    category: 'MEP & HVAC',
    fileType: 'PDF',
    size: '3.6 MB',
    uploadedAt: '20 Jul 2026',
    uploadedBy: 'Studio Atelier',
  },
  {
    id: 'file-5',
    projectId: 'proj-1',
    name: 'Shah_Residence_Approved_BOQ_v2.xlsx',
    category: 'Finishes & BOQ',
    fileType: 'XLSX',
    size: '840 KB',
    uploadedAt: '08 Jun 2026',
    uploadedBy: 'Studio Commercials',
  },
  {
    id: 'file-6',
    projectId: 'proj-1',
    name: 'Living_Dining_Photorealistic_3D_Renders.zip',
    category: '3D Renders',
    fileType: 'ZIP',
    size: '28.5 MB',
    uploadedAt: '15 Jun 2026',
    uploadedBy: '3D Studio Vis',
  },

  // Patel Office
  {
    id: 'file-7',
    projectId: 'proj-2',
    name: 'Apex_HQ_GFC_Partition_Layout_Rev3B.dwg',
    category: 'Drawings & CAD',
    fileType: 'DWG',
    size: '18.6 MB',
    uploadedAt: '10 May 2026',
    uploadedBy: 'Design Principal',
  },
  {
    id: 'file-8',
    projectId: 'proj-2',
    name: 'Server_Room_HVAC_Fire_Suppression_Specs.pdf',
    category: 'MEP & HVAC',
    fileType: 'PDF',
    size: '5.2 MB',
    uploadedAt: '25 May 2026',
    uploadedBy: 'MEP Consultant',
  },
  {
    id: 'file-9',
    projectId: 'proj-2',
    name: 'Boardroom_Fluted_Timber_Acoustic_Cutlist.pdf',
    category: 'Joinery & Millwork',
    fileType: 'PDF',
    size: '1.9 MB',
    uploadedAt: '12 Jul 2026',
    uploadedBy: 'DecoTimber',
  },

  // Mehta Villa
  {
    id: 'file-10',
    projectId: 'proj-3',
    name: 'Mandwa_Villa_Civil_Structural_AsBuilt.dwg',
    category: 'Drawings & CAD',
    fileType: 'DWG',
    size: '22.4 MB',
    uploadedAt: '15 Jul 2026',
    uploadedBy: 'Archana Sengupta',
  },
  {
    id: 'file-11',
    projectId: 'proj-3',
    name: 'Courtyard_Waterproofing_Ponding_Specs.pdf',
    category: 'Finishes & BOQ',
    fileType: 'PDF',
    size: '1.4 MB',
    uploadedAt: '02 Aug 2026',
    uploadedBy: 'Fosroc Tech',
  },
];
